# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(629, 476)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 255);")
        MainWindow.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNoTextHandles)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 591, 431))
        self.widget.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.widget.setObjectName("widget")
        self.password_lenght = QtWidgets.QSpinBox(parent=self.widget)
        self.password_lenght.setGeometry(QtCore.QRect(20, 30, 41, 31))
        self.password_lenght.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(170, 255, 0);\n"
"gridline-color: rgb(0, 85, 255);\n"
"color: rgb(0, 0, 255);\n"
"border-radius: 5px")
        self.password_lenght.setObjectName("password_lenght")
        self.password_count = QtWidgets.QSpinBox(parent=self.widget)
        self.password_count.setGeometry(QtCore.QRect(20, 80, 41, 31))
        self.password_count.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"gridline-color: rgb(0, 85, 255);\n"
"color: rgb(0, 0, 255);\n"
"border-radius: 5px")
        self.password_count.setObjectName("password_count")
        self.label_2_pass_lenght = QtWidgets.QLabel(parent=self.widget)
        self.label_2_pass_lenght.setGeometry(QtCore.QRect(80, 40, 91, 16))
        self.label_2_pass_lenght.setStyleSheet("color: rgb(170, 255, 0);")
        self.label_2_pass_lenght.setObjectName("label_2_pass_lenght")
        self.label_8_passs_count = QtWidgets.QLabel(parent=self.widget)
        self.label_8_passs_count.setGeometry(QtCore.QRect(80, 90, 131, 16))
        self.label_8_passs_count.setStyleSheet("color: rgb(170, 255, 0);")
        self.label_8_passs_count.setObjectName("label_8_passs_count")
        self.pushButton_add_upper = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add_upper.setGeometry(QtCore.QRect(20, 130, 161, 31))
        self.pushButton_add_upper.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.pushButton_add_upper.setAutoFillBackground(False)
        self.pushButton_add_upper.setStyleSheet("\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(170, 255, 0);\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_add_upper.setCheckable(False)
        self.pushButton_add_upper.setObjectName("pushButton_add_upper")
        self.pushButton_add_small = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add_small.setGeometry(QtCore.QRect(20, 180, 161, 31))
        self.pushButton_add_small.setMouseTracking(False)
        self.pushButton_add_small.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_add_small.setStyleSheet("\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(255, 85, 0);\n"
"")
        self.pushButton_add_small.setCheckable(False)
        self.pushButton_add_small.setObjectName("pushButton_add_small")
        self.pushButton_add_digitts = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add_digitts.setGeometry(QtCore.QRect(20, 230, 161, 31))
        self.pushButton_add_digitts.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.pushButton_add_digitts.setStyleSheet("\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 85, 255);\n"
"\n"
"\n"
"")
        self.pushButton_add_digitts.setCheckable(False)
        self.pushButton_add_digitts.setObjectName("pushButton_add_digitts")
        self.pushButton_add_punct = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add_punct.setGeometry(QtCore.QRect(20, 280, 161, 31))
        self.pushButton_add_punct.setStyleSheet("alternate-background-color: rgb(170, 255, 0);\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(170, 255, 0);\n"
"\n"
"")
        self.pushButton_add_punct.setCheckable(False)
        self.pushButton_add_punct.setObjectName("pushButton_add_punct")
        self.pushButton_add_del_chars = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add_del_chars.setGeometry(QtCore.QRect(20, 330, 161, 31))
        self.pushButton_add_del_chars.setStyleSheet("\n"
"background-color: rgb(255, 170, 0);\n"
"\n"
"color: rgb(0, 85, 127);\n"
"")
        self.pushButton_add_del_chars.setCheckable(False)
        self.pushButton_add_del_chars.setObjectName("pushButton_add_del_chars")
        self.pushButton_generate = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_generate.setEnabled(True)
        self.pushButton_generate.setGeometry(QtCore.QRect(320, 20, 161, 31))
        self.pushButton_generate.setStyleSheet("\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(170, 255, 0);\n"
"\n"
"border - width: 10 px;\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pushButton_generate.setCheckable(False)
        self.pushButton_generate.setAutoDefault(False)
        self.pushButton_generate.setDefault(False)
        self.pushButton_generate.setFlat(False)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.listWidget = QtWidgets.QListWidget(parent=self.widget)
        self.listWidget.setGeometry(QtCore.QRect(255, 70, 301, 281))
        self.listWidget.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.pushButtonSubmit = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(20, 380, 161, 31))
        self.pushButtonSubmit.setMouseTracking(False)
        self.pushButtonSubmit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonSubmit.setStyleSheet("\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(255, 85, 0);\n"
"")
        self.pushButtonSubmit.setCheckable(False)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2_pass_lenght.setText(_translate("MainWindow", "Длина пароля?"))
        self.label_8_passs_count.setText(_translate("MainWindow", "Количество паролей ?"))
        self.pushButton_add_upper.setText(_translate("MainWindow", "Добавить заглавые буквы"))
        self.pushButton_add_small.setText(_translate("MainWindow", "Добавить строчные буквы"))
        self.pushButton_add_digitts.setText(_translate("MainWindow", "Добавить цифры"))
        self.pushButton_add_punct.setText(_translate("MainWindow", "Добавить пунктуацию"))
        self.pushButton_add_del_chars.setText(_translate("MainWindow", "Удалить спорные символы"))
        self.pushButton_generate.setText(_translate("MainWindow", "Сгенерировать"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Применить "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
